//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumoServicio.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class InfoVariable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumoServicio.ServiceReference2.Variable[] VariablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumoServicio.ServiceReference2.Var[] CambioDiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumoServicio.ServiceReference2.VarDolar[] CambioDolarField;
        
        private int TotalItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ConsumoServicio.ServiceReference2.Variable[] Variables {
            get {
                return this.VariablesField;
            }
            set {
                if ((object.ReferenceEquals(this.VariablesField, value) != true)) {
                    this.VariablesField = value;
                    this.RaisePropertyChanged("Variables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ConsumoServicio.ServiceReference2.Var[] CambioDia {
            get {
                return this.CambioDiaField;
            }
            set {
                if ((object.ReferenceEquals(this.CambioDiaField, value) != true)) {
                    this.CambioDiaField = value;
                    this.RaisePropertyChanged("CambioDia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ConsumoServicio.ServiceReference2.VarDolar[] CambioDolar {
            get {
                return this.CambioDolarField;
            }
            set {
                if ((object.ReferenceEquals(this.CambioDolarField, value) != true)) {
                    this.CambioDolarField = value;
                    this.RaisePropertyChanged("CambioDolar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalItems {
            get {
                return this.TotalItemsField;
            }
            set {
                if ((this.TotalItemsField.Equals(value) != true)) {
                    this.TotalItemsField = value;
                    this.RaisePropertyChanged("TotalItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Variable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class Variable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda {
            get {
                return this.monedaField;
            }
            set {
                if ((this.monedaField.Equals(value) != true)) {
                    this.monedaField = value;
                    this.RaisePropertyChanged("moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Var", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class Var : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int monedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        private float ventaField;
        
        private float compraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda {
            get {
                return this.monedaField;
            }
            set {
                if ((this.monedaField.Equals(value) != true)) {
                    this.monedaField = value;
                    this.RaisePropertyChanged("moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float venta {
            get {
                return this.ventaField;
            }
            set {
                if ((this.ventaField.Equals(value) != true)) {
                    this.ventaField = value;
                    this.RaisePropertyChanged("venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float compra {
            get {
                return this.compraField;
            }
            set {
                if ((this.compraField.Equals(value) != true)) {
                    this.compraField = value;
                    this.RaisePropertyChanged("compra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VarDolar", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class VarDolar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        private float referenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float referencia {
            get {
                return this.referenciaField;
            }
            set {
                if ((this.referenciaField.Equals(value) != true)) {
                    this.referenciaField = value;
                    this.RaisePropertyChanged("referencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    [System.SerializableAttribute()]
    public partial class DataVariable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumoServicio.ServiceReference2.Var[] VarsField;
        
        private int TotalItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ConsumoServicio.ServiceReference2.Var[] Vars {
            get {
                return this.VarsField;
            }
            set {
                if ((object.ReferenceEquals(this.VarsField, value) != true)) {
                    this.VarsField = value;
                    this.RaisePropertyChanged("Vars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TotalItems {
            get {
                return this.TotalItemsField;
            }
            set {
                if ((this.TotalItemsField.Equals(value) != true)) {
                    this.TotalItemsField = value;
                    this.RaisePropertyChanged("TotalItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/", ConfigurationName="ServiceReference2.TipoCambioSoap")]
    public interface TipoCambioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VariablesDisponiblesResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/VariablesDisponibles", ReplyAction="*")]
        ConsumoServicio.ServiceReference2.VariablesDisponiblesResponse VariablesDisponibles(ConsumoServicio.ServiceReference2.VariablesDisponiblesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/VariablesDisponibles", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.VariablesDisponiblesResponse> VariablesDisponiblesAsync(ConsumoServicio.ServiceReference2.VariablesDisponiblesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VariablesResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/Variables", ReplyAction="*")]
        ConsumoServicio.ServiceReference2.VariablesResponse Variables(ConsumoServicio.ServiceReference2.VariablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/Variables", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.VariablesResponse> VariablesAsync(ConsumoServicio.ServiceReference2.VariablesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial", ReplyAction="*")]
        ConsumoServicio.ServiceReference2.TipoCambioFechaInicialResponse TipoCambioFechaInicial(ConsumoServicio.ServiceReference2.TipoCambioFechaInicialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(ConsumoServicio.ServiceReference2.TipoCambioFechaInicialRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRango", ReplyAction="*")]
        ConsumoServicio.ServiceReference2.TipoCambioRangoResponse TipoCambioRango(ConsumoServicio.ServiceReference2.TipoCambioRangoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRango", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioRangoResponse> TipoCambioRangoAsync(ConsumoServicio.ServiceReference2.TipoCambioRangoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda", ReplyAction="*")]
        ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaResponse TipoCambioFechaInicialMoneda(ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fechainit del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda", ReplyAction="*")]
        ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaResponse TipoCambioRangoMoneda(ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TipoCambioDiaResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDia", ReplyAction="*")]
        ConsumoServicio.ServiceReference2.TipoCambioDiaResponse TipoCambioDia(ConsumoServicio.ServiceReference2.TipoCambioDiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDia", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioDiaResponse> TipoCambioDiaAsync(ConsumoServicio.ServiceReference2.TipoCambioDiaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TipoCambioDiaStringResult del espacio de nombres http://www.banguat.gob.gt/variables/ws/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString", ReplyAction="*")]
        ConsumoServicio.ServiceReference2.TipoCambioDiaStringResponse TipoCambioDiaString(ConsumoServicio.ServiceReference2.TipoCambioDiaStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync(ConsumoServicio.ServiceReference2.TipoCambioDiaStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponibles", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public ConsumoServicio.ServiceReference2.VariablesDisponiblesRequestBody Body;
        
        public VariablesDisponiblesRequest() {
        }
        
        public VariablesDisponiblesRequest(ConsumoServicio.ServiceReference2.VariablesDisponiblesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class VariablesDisponiblesRequestBody {
        
        public VariablesDisponiblesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponiblesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public ConsumoServicio.ServiceReference2.VariablesDisponiblesResponseBody Body;
        
        public VariablesDisponiblesResponse() {
        }
        
        public VariablesDisponiblesResponse(ConsumoServicio.ServiceReference2.VariablesDisponiblesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesDisponiblesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumoServicio.ServiceReference2.InfoVariable VariablesDisponiblesResult;
        
        public VariablesDisponiblesResponseBody() {
        }
        
        public VariablesDisponiblesResponseBody(ConsumoServicio.ServiceReference2.InfoVariable VariablesDisponiblesResult) {
            this.VariablesDisponiblesResult = VariablesDisponiblesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Variables", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public ConsumoServicio.ServiceReference2.VariablesRequestBody Body;
        
        public VariablesRequest() {
        }
        
        public VariablesRequest(ConsumoServicio.ServiceReference2.VariablesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int variable;
        
        public VariablesRequestBody() {
        }
        
        public VariablesRequestBody(int variable) {
            this.variable = variable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public ConsumoServicio.ServiceReference2.VariablesResponseBody Body;
        
        public VariablesResponse() {
        }
        
        public VariablesResponse(ConsumoServicio.ServiceReference2.VariablesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumoServicio.ServiceReference2.InfoVariable VariablesResult;
        
        public VariablesResponseBody() {
        }
        
        public VariablesResponseBody(ConsumoServicio.ServiceReference2.InfoVariable VariablesResult) {
            this.VariablesResult = VariablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicial", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public ConsumoServicio.ServiceReference2.TipoCambioFechaInicialRequestBody Body;
        
        public TipoCambioFechaInicialRequest() {
        }
        
        public TipoCambioFechaInicialRequest(ConsumoServicio.ServiceReference2.TipoCambioFechaInicialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        public TipoCambioFechaInicialRequestBody() {
        }
        
        public TipoCambioFechaInicialRequestBody(string fechainit) {
            this.fechainit = fechainit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public ConsumoServicio.ServiceReference2.TipoCambioFechaInicialResponseBody Body;
        
        public TipoCambioFechaInicialResponse() {
        }
        
        public TipoCambioFechaInicialResponse(ConsumoServicio.ServiceReference2.TipoCambioFechaInicialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumoServicio.ServiceReference2.DataVariable TipoCambioFechaInicialResult;
        
        public TipoCambioFechaInicialResponseBody() {
        }
        
        public TipoCambioFechaInicialResponseBody(ConsumoServicio.ServiceReference2.DataVariable TipoCambioFechaInicialResult) {
            this.TipoCambioFechaInicialResult = TipoCambioFechaInicialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRango", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public ConsumoServicio.ServiceReference2.TipoCambioRangoRequestBody Body;
        
        public TipoCambioRangoRequest() {
        }
        
        public TipoCambioRangoRequest(ConsumoServicio.ServiceReference2.TipoCambioRangoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        public TipoCambioRangoRequestBody() {
        }
        
        public TipoCambioRangoRequestBody(string fechainit, string fechafin) {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public ConsumoServicio.ServiceReference2.TipoCambioRangoResponseBody Body;
        
        public TipoCambioRangoResponse() {
        }
        
        public TipoCambioRangoResponse(ConsumoServicio.ServiceReference2.TipoCambioRangoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumoServicio.ServiceReference2.DataVariable TipoCambioRangoResult;
        
        public TipoCambioRangoResponseBody() {
        }
        
        public TipoCambioRangoResponseBody(ConsumoServicio.ServiceReference2.DataVariable TipoCambioRangoResult) {
            this.TipoCambioRangoResult = TipoCambioRangoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaRequestBody Body;
        
        public TipoCambioFechaInicialMonedaRequest() {
        }
        
        public TipoCambioFechaInicialMonedaRequest(ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int moneda;
        
        public TipoCambioFechaInicialMonedaRequestBody() {
        }
        
        public TipoCambioFechaInicialMonedaRequestBody(string fechainit, int moneda) {
            this.fechainit = fechainit;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaResponseBody Body;
        
        public TipoCambioFechaInicialMonedaResponse() {
        }
        
        public TipoCambioFechaInicialMonedaResponse(ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumoServicio.ServiceReference2.DataVariable TipoCambioFechaInicialMonedaResult;
        
        public TipoCambioFechaInicialMonedaResponseBody() {
        }
        
        public TipoCambioFechaInicialMonedaResponseBody(ConsumoServicio.ServiceReference2.DataVariable TipoCambioFechaInicialMonedaResult) {
            this.TipoCambioFechaInicialMonedaResult = TipoCambioFechaInicialMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaRequestBody Body;
        
        public TipoCambioRangoMonedaRequest() {
        }
        
        public TipoCambioRangoMonedaRequest(ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int moneda;
        
        public TipoCambioRangoMonedaRequestBody() {
        }
        
        public TipoCambioRangoMonedaRequestBody(string fechainit, string fechafin, int moneda) {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaResponseBody Body;
        
        public TipoCambioRangoMonedaResponse() {
        }
        
        public TipoCambioRangoMonedaResponse(ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumoServicio.ServiceReference2.DataVariable TipoCambioRangoMonedaResult;
        
        public TipoCambioRangoMonedaResponseBody() {
        }
        
        public TipoCambioRangoMonedaResponseBody(ConsumoServicio.ServiceReference2.DataVariable TipoCambioRangoMonedaResult) {
            this.TipoCambioRangoMonedaResult = TipoCambioRangoMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDia", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public ConsumoServicio.ServiceReference2.TipoCambioDiaRequestBody Body;
        
        public TipoCambioDiaRequest() {
        }
        
        public TipoCambioDiaRequest(ConsumoServicio.ServiceReference2.TipoCambioDiaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaRequestBody {
        
        public TipoCambioDiaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public ConsumoServicio.ServiceReference2.TipoCambioDiaResponseBody Body;
        
        public TipoCambioDiaResponse() {
        }
        
        public TipoCambioDiaResponse(ConsumoServicio.ServiceReference2.TipoCambioDiaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumoServicio.ServiceReference2.InfoVariable TipoCambioDiaResult;
        
        public TipoCambioDiaResponseBody() {
        }
        
        public TipoCambioDiaResponseBody(ConsumoServicio.ServiceReference2.InfoVariable TipoCambioDiaResult) {
            this.TipoCambioDiaResult = TipoCambioDiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaString", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public ConsumoServicio.ServiceReference2.TipoCambioDiaStringRequestBody Body;
        
        public TipoCambioDiaStringRequest() {
        }
        
        public TipoCambioDiaStringRequest(ConsumoServicio.ServiceReference2.TipoCambioDiaStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaStringRequestBody {
        
        public TipoCambioDiaStringRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaStringResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public ConsumoServicio.ServiceReference2.TipoCambioDiaStringResponseBody Body;
        
        public TipoCambioDiaStringResponse() {
        }
        
        public TipoCambioDiaStringResponse(ConsumoServicio.ServiceReference2.TipoCambioDiaStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TipoCambioDiaStringResult;
        
        public TipoCambioDiaStringResponseBody() {
        }
        
        public TipoCambioDiaStringResponseBody(string TipoCambioDiaStringResult) {
            this.TipoCambioDiaStringResult = TipoCambioDiaStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TipoCambioSoapChannel : ConsumoServicio.ServiceReference2.TipoCambioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoCambioSoapClient : System.ServiceModel.ClientBase<ConsumoServicio.ServiceReference2.TipoCambioSoap>, ConsumoServicio.ServiceReference2.TipoCambioSoap {
        
        public TipoCambioSoapClient() {
        }
        
        public TipoCambioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoCambioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoCambioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoCambioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoServicio.ServiceReference2.VariablesDisponiblesResponse ConsumoServicio.ServiceReference2.TipoCambioSoap.VariablesDisponibles(ConsumoServicio.ServiceReference2.VariablesDisponiblesRequest request) {
            return base.Channel.VariablesDisponibles(request);
        }
        
        public ConsumoServicio.ServiceReference2.InfoVariable VariablesDisponibles() {
            ConsumoServicio.ServiceReference2.VariablesDisponiblesRequest inValue = new ConsumoServicio.ServiceReference2.VariablesDisponiblesRequest();
            inValue.Body = new ConsumoServicio.ServiceReference2.VariablesDisponiblesRequestBody();
            ConsumoServicio.ServiceReference2.VariablesDisponiblesResponse retVal = ((ConsumoServicio.ServiceReference2.TipoCambioSoap)(this)).VariablesDisponibles(inValue);
            return retVal.Body.VariablesDisponiblesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.VariablesDisponiblesResponse> ConsumoServicio.ServiceReference2.TipoCambioSoap.VariablesDisponiblesAsync(ConsumoServicio.ServiceReference2.VariablesDisponiblesRequest request) {
            return base.Channel.VariablesDisponiblesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.VariablesDisponiblesResponse> VariablesDisponiblesAsync() {
            ConsumoServicio.ServiceReference2.VariablesDisponiblesRequest inValue = new ConsumoServicio.ServiceReference2.VariablesDisponiblesRequest();
            inValue.Body = new ConsumoServicio.ServiceReference2.VariablesDisponiblesRequestBody();
            return ((ConsumoServicio.ServiceReference2.TipoCambioSoap)(this)).VariablesDisponiblesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoServicio.ServiceReference2.VariablesResponse ConsumoServicio.ServiceReference2.TipoCambioSoap.Variables(ConsumoServicio.ServiceReference2.VariablesRequest request) {
            return base.Channel.Variables(request);
        }
        
        public ConsumoServicio.ServiceReference2.InfoVariable Variables(int variable) {
            ConsumoServicio.ServiceReference2.VariablesRequest inValue = new ConsumoServicio.ServiceReference2.VariablesRequest();
            inValue.Body = new ConsumoServicio.ServiceReference2.VariablesRequestBody();
            inValue.Body.variable = variable;
            ConsumoServicio.ServiceReference2.VariablesResponse retVal = ((ConsumoServicio.ServiceReference2.TipoCambioSoap)(this)).Variables(inValue);
            return retVal.Body.VariablesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.VariablesResponse> ConsumoServicio.ServiceReference2.TipoCambioSoap.VariablesAsync(ConsumoServicio.ServiceReference2.VariablesRequest request) {
            return base.Channel.VariablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.VariablesResponse> VariablesAsync(int variable) {
            ConsumoServicio.ServiceReference2.VariablesRequest inValue = new ConsumoServicio.ServiceReference2.VariablesRequest();
            inValue.Body = new ConsumoServicio.ServiceReference2.VariablesRequestBody();
            inValue.Body.variable = variable;
            return ((ConsumoServicio.ServiceReference2.TipoCambioSoap)(this)).VariablesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoServicio.ServiceReference2.TipoCambioFechaInicialResponse ConsumoServicio.ServiceReference2.TipoCambioSoap.TipoCambioFechaInicial(ConsumoServicio.ServiceReference2.TipoCambioFechaInicialRequest request) {
            return base.Channel.TipoCambioFechaInicial(request);
        }
        
        public ConsumoServicio.ServiceReference2.DataVariable TipoCambioFechaInicial(string fechainit) {
            ConsumoServicio.ServiceReference2.TipoCambioFechaInicialRequest inValue = new ConsumoServicio.ServiceReference2.TipoCambioFechaInicialRequest();
            inValue.Body = new ConsumoServicio.ServiceReference2.TipoCambioFechaInicialRequestBody();
            inValue.Body.fechainit = fechainit;
            ConsumoServicio.ServiceReference2.TipoCambioFechaInicialResponse retVal = ((ConsumoServicio.ServiceReference2.TipoCambioSoap)(this)).TipoCambioFechaInicial(inValue);
            return retVal.Body.TipoCambioFechaInicialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioFechaInicialResponse> ConsumoServicio.ServiceReference2.TipoCambioSoap.TipoCambioFechaInicialAsync(ConsumoServicio.ServiceReference2.TipoCambioFechaInicialRequest request) {
            return base.Channel.TipoCambioFechaInicialAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(string fechainit) {
            ConsumoServicio.ServiceReference2.TipoCambioFechaInicialRequest inValue = new ConsumoServicio.ServiceReference2.TipoCambioFechaInicialRequest();
            inValue.Body = new ConsumoServicio.ServiceReference2.TipoCambioFechaInicialRequestBody();
            inValue.Body.fechainit = fechainit;
            return ((ConsumoServicio.ServiceReference2.TipoCambioSoap)(this)).TipoCambioFechaInicialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoServicio.ServiceReference2.TipoCambioRangoResponse ConsumoServicio.ServiceReference2.TipoCambioSoap.TipoCambioRango(ConsumoServicio.ServiceReference2.TipoCambioRangoRequest request) {
            return base.Channel.TipoCambioRango(request);
        }
        
        public ConsumoServicio.ServiceReference2.DataVariable TipoCambioRango(string fechainit, string fechafin) {
            ConsumoServicio.ServiceReference2.TipoCambioRangoRequest inValue = new ConsumoServicio.ServiceReference2.TipoCambioRangoRequest();
            inValue.Body = new ConsumoServicio.ServiceReference2.TipoCambioRangoRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            ConsumoServicio.ServiceReference2.TipoCambioRangoResponse retVal = ((ConsumoServicio.ServiceReference2.TipoCambioSoap)(this)).TipoCambioRango(inValue);
            return retVal.Body.TipoCambioRangoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioRangoResponse> ConsumoServicio.ServiceReference2.TipoCambioSoap.TipoCambioRangoAsync(ConsumoServicio.ServiceReference2.TipoCambioRangoRequest request) {
            return base.Channel.TipoCambioRangoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioRangoResponse> TipoCambioRangoAsync(string fechainit, string fechafin) {
            ConsumoServicio.ServiceReference2.TipoCambioRangoRequest inValue = new ConsumoServicio.ServiceReference2.TipoCambioRangoRequest();
            inValue.Body = new ConsumoServicio.ServiceReference2.TipoCambioRangoRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            return ((ConsumoServicio.ServiceReference2.TipoCambioSoap)(this)).TipoCambioRangoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaResponse ConsumoServicio.ServiceReference2.TipoCambioSoap.TipoCambioFechaInicialMoneda(ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaRequest request) {
            return base.Channel.TipoCambioFechaInicialMoneda(request);
        }
        
        public ConsumoServicio.ServiceReference2.DataVariable TipoCambioFechaInicialMoneda(string fechainit, int moneda) {
            ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaRequest inValue = new ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaRequest();
            inValue.Body = new ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.moneda = moneda;
            ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaResponse retVal = ((ConsumoServicio.ServiceReference2.TipoCambioSoap)(this)).TipoCambioFechaInicialMoneda(inValue);
            return retVal.Body.TipoCambioFechaInicialMonedaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaResponse> ConsumoServicio.ServiceReference2.TipoCambioSoap.TipoCambioFechaInicialMonedaAsync(ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaRequest request) {
            return base.Channel.TipoCambioFechaInicialMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(string fechainit, int moneda) {
            ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaRequest inValue = new ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaRequest();
            inValue.Body = new ConsumoServicio.ServiceReference2.TipoCambioFechaInicialMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.moneda = moneda;
            return ((ConsumoServicio.ServiceReference2.TipoCambioSoap)(this)).TipoCambioFechaInicialMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaResponse ConsumoServicio.ServiceReference2.TipoCambioSoap.TipoCambioRangoMoneda(ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaRequest request) {
            return base.Channel.TipoCambioRangoMoneda(request);
        }
        
        public ConsumoServicio.ServiceReference2.DataVariable TipoCambioRangoMoneda(string fechainit, string fechafin, int moneda) {
            ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaRequest inValue = new ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaRequest();
            inValue.Body = new ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            inValue.Body.moneda = moneda;
            ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaResponse retVal = ((ConsumoServicio.ServiceReference2.TipoCambioSoap)(this)).TipoCambioRangoMoneda(inValue);
            return retVal.Body.TipoCambioRangoMonedaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaResponse> ConsumoServicio.ServiceReference2.TipoCambioSoap.TipoCambioRangoMonedaAsync(ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaRequest request) {
            return base.Channel.TipoCambioRangoMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(string fechainit, string fechafin, int moneda) {
            ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaRequest inValue = new ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaRequest();
            inValue.Body = new ConsumoServicio.ServiceReference2.TipoCambioRangoMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            inValue.Body.moneda = moneda;
            return ((ConsumoServicio.ServiceReference2.TipoCambioSoap)(this)).TipoCambioRangoMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoServicio.ServiceReference2.TipoCambioDiaResponse ConsumoServicio.ServiceReference2.TipoCambioSoap.TipoCambioDia(ConsumoServicio.ServiceReference2.TipoCambioDiaRequest request) {
            return base.Channel.TipoCambioDia(request);
        }
        
        public ConsumoServicio.ServiceReference2.InfoVariable TipoCambioDia() {
            ConsumoServicio.ServiceReference2.TipoCambioDiaRequest inValue = new ConsumoServicio.ServiceReference2.TipoCambioDiaRequest();
            inValue.Body = new ConsumoServicio.ServiceReference2.TipoCambioDiaRequestBody();
            ConsumoServicio.ServiceReference2.TipoCambioDiaResponse retVal = ((ConsumoServicio.ServiceReference2.TipoCambioSoap)(this)).TipoCambioDia(inValue);
            return retVal.Body.TipoCambioDiaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioDiaResponse> ConsumoServicio.ServiceReference2.TipoCambioSoap.TipoCambioDiaAsync(ConsumoServicio.ServiceReference2.TipoCambioDiaRequest request) {
            return base.Channel.TipoCambioDiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioDiaResponse> TipoCambioDiaAsync() {
            ConsumoServicio.ServiceReference2.TipoCambioDiaRequest inValue = new ConsumoServicio.ServiceReference2.TipoCambioDiaRequest();
            inValue.Body = new ConsumoServicio.ServiceReference2.TipoCambioDiaRequestBody();
            return ((ConsumoServicio.ServiceReference2.TipoCambioSoap)(this)).TipoCambioDiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoServicio.ServiceReference2.TipoCambioDiaStringResponse ConsumoServicio.ServiceReference2.TipoCambioSoap.TipoCambioDiaString(ConsumoServicio.ServiceReference2.TipoCambioDiaStringRequest request) {
            return base.Channel.TipoCambioDiaString(request);
        }
        
        public string TipoCambioDiaString() {
            ConsumoServicio.ServiceReference2.TipoCambioDiaStringRequest inValue = new ConsumoServicio.ServiceReference2.TipoCambioDiaStringRequest();
            inValue.Body = new ConsumoServicio.ServiceReference2.TipoCambioDiaStringRequestBody();
            ConsumoServicio.ServiceReference2.TipoCambioDiaStringResponse retVal = ((ConsumoServicio.ServiceReference2.TipoCambioSoap)(this)).TipoCambioDiaString(inValue);
            return retVal.Body.TipoCambioDiaStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioDiaStringResponse> ConsumoServicio.ServiceReference2.TipoCambioSoap.TipoCambioDiaStringAsync(ConsumoServicio.ServiceReference2.TipoCambioDiaStringRequest request) {
            return base.Channel.TipoCambioDiaStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoServicio.ServiceReference2.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync() {
            ConsumoServicio.ServiceReference2.TipoCambioDiaStringRequest inValue = new ConsumoServicio.ServiceReference2.TipoCambioDiaStringRequest();
            inValue.Body = new ConsumoServicio.ServiceReference2.TipoCambioDiaStringRequestBody();
            return ((ConsumoServicio.ServiceReference2.TipoCambioSoap)(this)).TipoCambioDiaStringAsync(inValue);
        }
    }
}
